branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      parserOpts: &a1
        - BREAKING CHANGE
        - BREAKING CHANGES
        - BREAKING
      releaseRules:
        - type: fix
          release: patch
        - type: fix
          release: patch
          scope: drv
        - type: fix
          release: false
          scope: config
        - type: new
          release: minor
        - type: update
          release: major
        - type: remove
          release: major
        - type: docs
          release: false
        - type: docs
          release: false
          scope: user
        - type: docs
          release: false
          scope: dev
        - type: docs
          release: patch
          scope: pkg
        - type: ci
          release: false
        - type: release
          release: false
        - type: config
          release: false
        - type: config
          release: false
          scope: lint
        - type: config
          release: false
          scope: fmt
        - type: config
          release: false
          scope: build
        - type: config
          release: false
          scope: nix
        - type: config
          release: false
          scope: env
        - type: config
          release: false
          scope: ignore
        - type: chore
          release: false
        - scope: no-release
          release: false
      presetConfig:
        types:
          - type: fix
            section: Bug Fixes
          - type: new
            section: New Packages
          - type: update
            section: Packages Updated
          - type: remove
            section: Removed Packages
          - type: docs
            section: Documentation Updates
          - type: ci
            hidden: true
          - type: release
            hidden: true
          - type: config
            hidden: true
          - type: chore
            hidden: true
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts: *a1
      writerOpts:
        commitsSort:
          - subject
          - scope
      presetConfig:
        types:
          - type: fix
            section: Bug Fixes
          - type: new
            section: New Packages
          - type: update
            section: Packages Updated
          - type: remove
            section: Removed Packages
          - type: docs
            section: Documentation Updates
          - type: ci
            hidden: true
          - type: release
            hidden: true
          - type: config
            hidden: true
          - type: chore
            hidden: true
  - - "@semantic-release/changelog"
    - changelogFile: docs/user/03-Changelog.md
      changelogTitle: |
        ---
        id: changelog
        title: Changelog
        ---
  - - "@semantic-release/git"
    - message: |-
        release: ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
      assets:
        - docs/**/*.*
  - "@semantic-release/github"
