repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shfmt
      - id: shellcheck
  - repo: local
    hooks:
      - id: ts-lint
        name: Lint TypeScript and JavaScript files
        entry: eslint -c ./config/.eslintrc.js --fix
        files: ^(src|tests)/.*\.(js|ts|json|jsx|tsx)$
        pass_filenames: true
        language: system

      - id: tsc-lint
        name: Lint TypeScript
        entry: tsc --noEmit
        files: ^(src|tests)/.*\.(js|ts|json|jsx|tsx)$
        pass_filenames: false
        language: system

      - id: docker-lint
        name: Lint Docker files
        entry: hadolint
        files: ^.*Dockerfile$
        pass_filenames: true
        language: system

      - id: cfg-scripts
        name: Configure Scripts
        entry: pls cfg:scripts
        files: ^.*\.sh$
        pass_filenames: false
        language: system

      - id: yaml-fmt
        name: Format YAML with prettier
        entry: prettier -w
        files: ^.*\.(yaml|yml)$
        pass_filenames: true
        language: system

      - id: md-fmt
        name: Format Markdown with prettier
        entry: prettier -w
        files: ^.*\.(MD|md)$
        pass_filenames: true
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: nixpkgs-fmt
        files: ^.*\.nix$
        language: system
        pass_filenames: true

      - id: gitlint-linter
        name: Lints Gitlint to conform to atomi_release.yaml
        entry: sg gitlint
        files: (atomi_release.yaml|.gitlint)
        language: system
        pass_filenames: false

      - id: cfg-scripts
        name: Configure Scripts
        entry: pls cfg:scripts
        files: ^.*\.sh$
        pass_filenames: false
        language: system
