name: "Test Report"
on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed
jobs:
  Report:
    runs-on: ubuntu-20.04
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-reports-${{ github.sha }
          name: Jest Tests
          path: "junit.xml"
          reporter: jest-junit
