name: "Test Report"
on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed
jobs:
  Report:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Test Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-reports-${{ github.sha }
          path: junit.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Jest Tests
          path: "junit.xml"
          reporter: jest-junit
